##
# E2E testing Dockerfile
##

FROM cypress/base:18.15.0

WORKDIR /e2e

COPY ./test/package*.json /e2e
COPY ./test/cypress.config.js /e2e
COPY ./test/cypress /e2e/cypress

RUN npm ci

ENTRYPOINT [ "npx", "cypress", "run" ]