name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Authenticate Docker with Google Container Registry
      - name: Authenticate Docker with Google Container Registry
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.SERVICE_ACCOUNT_KEY }}
          gcloud auth configure-docker europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }} --quiet

      # Build and push Docker image to GCP Container Registry
      - name: Build and push Docker image
        run: |
          docker build -t europe-north1-docker.pkg.dev/dy-demo-projects/hedgehog-map-image .
          docker push europe-north1-docker.pkg.dev/dy-demo-projects/hedgehog-map-image
