name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Authenticate Docker with Google Container Registry
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }} --quiet

      - name: Build and push Docker image
        run: |
          docker build -t europe-north1-docker.pkg.dev/dy-demo-projects/hedgehog-map-image .
          docker push europe-north1-docker.pkg.dev/dy-demo-projects/hedgehog-map-image
