name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Authenticate Docker with GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and tag Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/my-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/my-app:${{ github.sha }}

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container my-instance \
            --container-image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/my-app:${{ github.sha }} \
            --zone us-central1-a
