name: End-to-End Tests

on:
  push:
    branches:
      - dev

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Compose
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit

      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
